/* =========================================================================
   بيانات وهمية واقعية بالعربية — للعرض فقط (MVP استعراضي)
   ملاحظة §15: لا يُولّد النظام أو يقترح أي أسعار. مبالغ الكراسة (كقيمة
   الضمان الابتدائي) تُعرض كـ"مُستخرَجة من الكراسة" لا كنص مولّد.
   ========================================================================= */
import type { Owner, Requirement, Tender } from "./types";

export const owners: Record<string, Owner> = {
  ahmad: { name: "أحمد المالكي", initials: "أم" },
  sara: { name: "سارة العنزي", initials: "سع" },
  faisal: { name: "فيصل القحطاني", initials: "فق" },
  noura: { name: "نورة الدوسري", initials: "ند" },
};

export const tenders: Tender[] = [
  {
    id: "t-442031",
    reference: "442031",
    title: "تشغيل وصيانة مرافق المجمّع الإداري",
    entity: "أمانة منطقة الرياض",
    sector: "تشغيل وصيانة",
    closingDate: "٢٨ رجب ١٤٤٧هـ",
    daysLeft: 6,
    stage: "بانتظار المراجعة",
    readiness: 75,
    requirementsCount: 8,
    gapsCount: 1,
  },
  {
    id: "t-440198",
    reference: "440198",
    title: "توريد وتركيب أنظمة الشبكات والاتصالات",
    entity: "وزارة الموارد البشرية والتنمية الاجتماعية",
    sector: "تقنية المعلومات",
    closingDate: "١١ شعبان ١٤٤٧هـ",
    daysLeft: 19,
    stage: "قيد المعالجة",
    readiness: 28,
    requirementsCount: 31,
    gapsCount: 9,
  },
  {
    id: "t-439770",
    reference: "439770",
    title: "أعمال إنشاء وتأهيل طرق فرعية — المرحلة الثانية",
    entity: "وزارة النقل والخدمات اللوجستية",
    sector: "مقاولات",
    closingDate: "٣ رمضان ١٤٤٧هـ",
    daysLeft: 41,
    stage: "جاهزة",
    readiness: 96,
    requirementsCount: 27,
    gapsCount: 0,
  },
  {
    id: "t-438402",
    reference: "438402",
    title: "خدمات استشارية لإعداد دراسات الأثر البيئي",
    entity: "المركز الوطني للرقابة على الالتزام البيئي",
    sector: "استشارات",
    closingDate: "١٧ جمادى الآخرة ١٤٤٧هـ",
    daysLeft: 2,
    stage: "بانتظار المراجعة",
    readiness: 61,
    requirementsCount: 18,
    gapsCount: 4,
  },
  {
    id: "t-437955",
    reference: "437955",
    title: "توريد أجهزة ومستلزمات مخبرية",
    entity: "هيئة الغذاء والدواء",
    sector: "توريد",
    closingDate: "٢٢ شعبان ١٤٤٧هـ",
    daysLeft: 30,
    stage: "تم التصدير",
    readiness: 100,
    requirementsCount: 15,
    gapsCount: 0,
  },
];

/** متطلبات مصفوفة التجهيز للمنافسة 442031 (الشاشة المحورية) */
export const requirements: Requirement[] = [
  {
    id: "r-01",
    title: "الضمان الابتدائي (البنكي)",
    detail: "ضمان بنكي غير مشروط ساري المفعول لمدة ٩٠ يوماً من تاريخ فتح العروض.",
    category: "مالي",
    status: "جاهز",
    priority: "عالية",
    needsAttachment: true,
    needsText: false,
    owner: owners.ahmad,
    confidence: 0.98,
    needsHumanReview: false,
    source: {
      fileName: "كراسة الشروط — الملحق ٣.pdf",
      page: 45,
      excerpt:
        "يُقدّم المنافس ضماناً ابتدائياً غير مشروط وغير قابل للإلغاء، صالحاً لمدة (٩٠) يوماً، بقيمة الضمان المحدّدة في هذا الملحق.",
    },
  },
  {
    id: "r-02",
    title: "شهادة السعودة (نطاقات)",
    detail: "شهادة سارية من وزارة الموارد البشرية تثبت النطاق الأخضر فأعلى.",
    category: "إداري",
    status: "قيد التجهيز",
    priority: "متوسطة",
    needsAttachment: true,
    needsText: false,
    owner: owners.sara,
    confidence: 0.91,
    needsHumanReview: false,
    source: {
      fileName: "كراسة الشروط الرئيسية.pdf",
      page: 12,
      excerpt:
        "يُرفق المنافس شهادة التزام سارية المفعول صادرة عن الوزارة، على ألا يقل النطاق عن الأخضر المتوسط.",
    },
  },
  {
    id: "r-03",
    title: "خطة الصيانة الوقائية السنوية",
    detail: "جدول تفصيلي للصيانة الدورية للمعدات والمرافق طوال مدة العقد.",
    category: "فني",
    status: "ناقص",
    priority: "عالية",
    needsAttachment: false,
    needsText: true,
    owner: null,
    confidence: 0.72,
    needsHumanReview: true,
    source: {
      fileName: "المواصفات الفنية.pdf",
      page: 78,
      excerpt:
        "يلتزم المتعهد بتقديم خطة صيانة وقائية سنوية تشمل جداول التدخل الدوري ومؤشرات الأداء.",
    },
  },
  {
    id: "r-04",
    title: "السجل التجاري ساري المفعول",
    detail: "نسخة من السجل التجاري متضمنة النشاط المطابق لمجال المنافسة.",
    category: "مرفق",
    status: "جاهز",
    priority: "متوسطة",
    needsAttachment: true,
    needsText: false,
    owner: owners.faisal,
    confidence: 0.99,
    needsHumanReview: false,
    source: {
      fileName: "كراسة الشروط الرئيسية.pdf",
      page: 9,
      excerpt:
        "يُرفق سجل تجاري ساري يتضمن نشاطاً مطابقاً لطبيعة الأعمال المطلوبة في المنافسة.",
    },
  },
  {
    id: "r-05",
    title: "موعد فتح المظاريف",
    detail: "حضور جلسة فتح العروض في الموعد والمكان المحدّدين دون تأخير.",
    category: "موعد",
    status: "يحتاج مراجعة",
    priority: "عالية",
    needsAttachment: false,
    needsText: false,
    owner: owners.noura,
    confidence: 0.84,
    needsHumanReview: true,
    source: {
      fileName: "كراسة الشروط الرئيسية.pdf",
      page: 4,
      excerpt:
        "يُفتح المظروف الفني في تمام الساعة المحددة، ولا يُلتفت لأي عرض يُقدَّم بعد الموعد.",
    },
  },
  {
    id: "r-06",
    title: "منهجية تنفيذ الأعمال",
    detail: "وصف منهجي لمراحل التنفيذ وآلية ضبط الجودة والتسليم.",
    category: "فني",
    status: "قيد التجهيز",
    priority: "متوسطة",
    needsAttachment: false,
    needsText: true,
    owner: owners.ahmad,
    confidence: 0.88,
    needsHumanReview: false,
    source: {
      fileName: "المواصفات الفنية.pdf",
      page: 33,
      excerpt:
        "يقدّم المنافس منهجية واضحة لتنفيذ نطاق العمل تشمل المراحل والموارد وضبط الجودة.",
    },
  },
  {
    id: "r-07",
    title: "خبرات سابقة مماثلة (٣ مشاريع)",
    detail: "شهادات إنجاز أو عقود لمشاريع مماثلة خلال السنوات الخمس الماضية.",
    category: "فني",
    status: "قيد التجهيز",
    priority: "متوسطة",
    needsAttachment: true,
    needsText: true,
    owner: owners.sara,
    confidence: 0.79,
    needsHumanReview: false,
    source: {
      fileName: "كراسة الشروط الرئيسية.pdf",
      page: 21,
      excerpt:
        "يُثبت المنافس خبرة سابقة في أعمال مماثلة بما لا يقل عن ثلاثة مشاريع خلال خمس سنوات.",
    },
  },
  {
    id: "r-08",
    title: "جدول الكميات (BOQ) — بدون أسعار",
    detail: "تعبئة بنود جدول الكميات وتنظيمها دون إدخال أي قيم سعرية.",
    category: "مالي",
    status: "جديد",
    priority: "عالية",
    needsAttachment: false,
    needsText: false,
    owner: null,
    confidence: 0.81,
    needsHumanReview: false,
    source: {
      fileName: "جدول الكميات.xlsx",
      page: 1,
      excerpt:
        "يلتزم المنافس بتعبئة جميع بنود جدول الكميات وفق الوحدات المحددة، وتقديمه مكتملاً.",
    },
  },
];
